### ISSUE TITLE
Wrong SRC to assets

### ISSUE THREAD

**Issue by a00andos** [brunch/with-es6#4]
Hey!

I think the SRC in the index file for the asset are wrong. 

```
link rel="stylesheet" href="/app.css">
<script src="/vendor.js"></script>
<script src="/app.js"></script>
```
Should it not be without be without the first / (slash) to successfully load the assets after a build:

```
link rel="stylesheet" href="app.css">
<script src="vendor.js"></script>
<script src="app.js"></script>
```

I believe this error also exist in the dead simple skeleton... Those two are the ones I tried before realizing this.

**Comment by nomuna** [comment]
Leading '/' is for the server. In other words when you start the skeleton app with

```
npm start
```

Of course if you want to load it from the disk the path is incorrect. So it is not a bug.
